/* 3초 여행 — Worldwide city dataset
 * Minimal pure-data module. Each entry: { key, name (한글), country, region, flag, tier, aliases }
 * tier ∈ {'high','mid','low'} — used for budget smart-suggestion.
 */
export const CITIES = [
  // 한국
  {key:'seoul',     name:'서울',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'mid', aliases:['Seoul']},
  {key:'busan',     name:'부산',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'mid', aliases:['Busan','Pusan']},
  {key:'jeju',      name:'제주',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'low', aliases:['Jeju']},
  {key:'gangneung', name:'강릉',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'low', aliases:['Gangneung']},
  {key:'gyeongju',  name:'경주',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'low', aliases:['Gyeongju']},
  {key:'sokcho',    name:'속초',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'low', aliases:['Sokcho']},
  {key:'jeonju',    name:'전주',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'low', aliases:['Jeonju']},
  {key:'yeosu',     name:'여수',     country:'대한민국', region:'아시아',   flag:'🇰🇷', tier:'low', aliases:['Yeosu']},

  // 일본
  {key:'tokyo',     name:'도쿄',     country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'high',aliases:['Tokyo','東京']},
  {key:'osaka',     name:'오사카',   country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Osaka','大阪']},
  {key:'kyoto',     name:'교토',     country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Kyoto','京都']},
  {key:'fukuoka',   name:'후쿠오카', country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Fukuoka','福岡']},
  {key:'sapporo',   name:'삿포로',   country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Sapporo','札幌','홋카이도']},
  {key:'nagoya',    name:'나고야',   country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Nagoya','名古屋']},
  {key:'yokohama',  name:'요코하마', country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Yokohama','横浜']},
  {key:'okinawa',   name:'오키나와', country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Okinawa','沖縄']},
  {key:'hiroshima', name:'히로시마', country:'일본',     region:'아시아',   flag:'🇯🇵', tier:'mid', aliases:['Hiroshima','広島']},

  // 중국 / 홍콩 / 대만
  {key:'beijing',   name:'베이징',   country:'중국',     region:'아시아',   flag:'🇨🇳', tier:'mid', aliases:['Beijing','北京']},
  {key:'shanghai',  name:'상하이',   country:'중국',     region:'아시아',   flag:'🇨🇳', tier:'mid', aliases:['Shanghai','上海']},
  {key:'chengdu',   name:'청두',     country:'중국',     region:'아시아',   flag:'🇨🇳', tier:'low', aliases:['Chengdu','成都']},
  {key:'hongkong',  name:'홍콩',     country:'홍콩',     region:'아시아',   flag:'🇭🇰', tier:'high',aliases:['Hong Kong','HK','香港']},
  {key:'taipei',    name:'타이베이', country:'대만',     region:'아시아',   flag:'🇹🇼', tier:'mid', aliases:['Taipei','臺北','대만']},
  {key:'kaohsiung', name:'가오슝',   country:'대만',     region:'아시아',   flag:'🇹🇼', tier:'low', aliases:['Kaohsiung','高雄']},
  {key:'macau',     name:'마카오',   country:'마카오',   region:'아시아',   flag:'🇲🇴', tier:'mid', aliases:['Macau','Macao']},

  // 동남아
  {key:'bangkok',   name:'방콕',     country:'태국',     region:'동남아',   flag:'🇹🇭', tier:'low', aliases:['Bangkok','BKK']},
  {key:'phuket',    name:'푸켓',     country:'태국',     region:'동남아',   flag:'🇹🇭', tier:'low', aliases:['Phuket']},
  {key:'chiangmai', name:'치앙마이', country:'태국',     region:'동남아',   flag:'🇹🇭', tier:'low', aliases:['Chiang Mai']},
  {key:'hanoi',     name:'하노이',   country:'베트남',   region:'동남아',   flag:'🇻🇳', tier:'low', aliases:['Hanoi','Hà Nội']},
  {key:'hochiminh', name:'호치민',   country:'베트남',   region:'동남아',   flag:'🇻🇳', tier:'low', aliases:['Ho Chi Minh','Saigon','사이공']},
  {key:'danang',    name:'다낭',     country:'베트남',   region:'동남아',   flag:'🇻🇳', tier:'low', aliases:['Da Nang','Danang']},
  {key:'singapore', name:'싱가포르', country:'싱가포르', region:'동남아',   flag:'🇸🇬', tier:'high',aliases:['Singapore','SG']},
  {key:'kualalumpur',name:'쿠알라룸푸르',country:'말레이시아',region:'동남아',flag:'🇲🇾', tier:'mid', aliases:['Kuala Lumpur','KL']},
  {key:'bali',      name:'발리',     country:'인도네시아',region:'동남아',   flag:'🇮🇩', tier:'mid', aliases:['Bali','Denpasar']},
  {key:'jakarta',   name:'자카르타', country:'인도네시아',region:'동남아',   flag:'🇮🇩', tier:'mid', aliases:['Jakarta']},
  {key:'cebu',      name:'세부',     country:'필리핀',   region:'동남아',   flag:'🇵🇭', tier:'low', aliases:['Cebu']},
  {key:'manila',    name:'마닐라',   country:'필리핀',   region:'동남아',   flag:'🇵🇭', tier:'low', aliases:['Manila']},
  {key:'siemreap',  name:'시엠립',   country:'캄보디아', region:'동남아',   flag:'🇰🇭', tier:'low', aliases:['Siem Reap','Angkor','앙코르']},

  // 남아시아
  {key:'mumbai',    name:'뭄바이',   country:'인도',     region:'남아시아', flag:'🇮🇳', tier:'mid', aliases:['Mumbai','Bombay']},
  {key:'delhi',     name:'델리',     country:'인도',     region:'남아시아', flag:'🇮🇳', tier:'mid', aliases:['Delhi','New Delhi']},
  {key:'colombo',   name:'콜롬보',   country:'스리랑카', region:'남아시아', flag:'🇱🇰', tier:'low', aliases:['Colombo']},
  {key:'kathmandu', name:'카트만두', country:'네팔',     region:'남아시아', flag:'🇳🇵', tier:'low', aliases:['Kathmandu']},

  // 유럽 — 서/남유럽
  {key:'paris',     name:'파리',     country:'프랑스',   region:'유럽',     flag:'🇫🇷', tier:'high',aliases:['Paris']},
  {key:'nice',      name:'니스',     country:'프랑스',   region:'유럽',     flag:'🇫🇷', tier:'high',aliases:['Nice']},
  {key:'london',    name:'런던',     country:'영국',     region:'유럽',     flag:'🇬🇧', tier:'high',aliases:['London']},
  {key:'edinburgh', name:'에든버러', country:'영국',     region:'유럽',     flag:'🇬🇧', tier:'mid', aliases:['Edinburgh']},
  {key:'rome',      name:'로마',     country:'이탈리아', region:'유럽',     flag:'🇮🇹', tier:'mid', aliases:['Rome','Roma']},
  {key:'venice',    name:'베네치아', country:'이탈리아', region:'유럽',     flag:'🇮🇹', tier:'high',aliases:['Venice','Venezia']},
  {key:'milan',     name:'밀라노',   country:'이탈리아', region:'유럽',     flag:'🇮🇹', tier:'high',aliases:['Milan','Milano']},
  {key:'florence',  name:'피렌체',   country:'이탈리아', region:'유럽',     flag:'🇮🇹', tier:'mid', aliases:['Florence','Firenze']},
  {key:'barcelona', name:'바르셀로나',country:'스페인',  region:'유럽',     flag:'🇪🇸', tier:'mid', aliases:['Barcelona']},
  {key:'madrid',    name:'마드리드', country:'스페인',   region:'유럽',     flag:'🇪🇸', tier:'mid', aliases:['Madrid']},
  {key:'lisbon',    name:'리스본',   country:'포르투갈', region:'유럽',     flag:'🇵🇹', tier:'mid', aliases:['Lisbon','Lisboa']},
  {key:'porto',     name:'포르투',   country:'포르투갈', region:'유럽',     flag:'🇵🇹', tier:'mid', aliases:['Porto']},
  {key:'amsterdam', name:'암스테르담',country:'네덜란드',region:'유럽',    flag:'🇳🇱', tier:'high',aliases:['Amsterdam']},
  {key:'brussels',  name:'브뤼셀',   country:'벨기에',   region:'유럽',     flag:'🇧🇪', tier:'high',aliases:['Brussels','Bruxelles']},
  {key:'zurich',    name:'취리히',   country:'스위스',   region:'유럽',     flag:'🇨🇭', tier:'high',aliases:['Zurich','Zürich']},
  {key:'interlaken',name:'인터라켄', country:'스위스',   region:'유럽',     flag:'🇨🇭', tier:'high',aliases:['Interlaken']},
  // 유럽 — 중/북/동
  {key:'berlin',    name:'베를린',   country:'독일',     region:'유럽',     flag:'🇩🇪', tier:'mid', aliases:['Berlin']},
  {key:'munich',    name:'뮌헨',     country:'독일',     region:'유럽',     flag:'🇩🇪', tier:'mid', aliases:['Munich','München']},
  {key:'frankfurt', name:'프랑크푸르트',country:'독일',  region:'유럽',     flag:'🇩🇪', tier:'mid', aliases:['Frankfurt']},
  {key:'vienna',    name:'비엔나',   country:'오스트리아',region:'유럽',    flag:'🇦🇹', tier:'mid', aliases:['Vienna','Wien']},
  {key:'prague',    name:'프라하',   country:'체코',     region:'유럽',     flag:'🇨🇿', tier:'low', aliases:['Prague','Praha']},
  {key:'budapest',  name:'부다페스트',country:'헝가리',  region:'유럽',     flag:'🇭🇺', tier:'low', aliases:['Budapest']},
  {key:'warsaw',    name:'바르샤바', country:'폴란드',   region:'유럽',     flag:'🇵🇱', tier:'low', aliases:['Warsaw','Warszawa']},
  {key:'stockholm', name:'스톡홀름', country:'스웨덴',   region:'유럽',     flag:'🇸🇪', tier:'high',aliases:['Stockholm']},
  {key:'copenhagen',name:'코펜하겐', country:'덴마크',   region:'유럽',     flag:'🇩🇰', tier:'high',aliases:['Copenhagen','København']},
  {key:'oslo',      name:'오슬로',   country:'노르웨이', region:'유럽',     flag:'🇳🇴', tier:'high',aliases:['Oslo']},
  {key:'helsinki',  name:'헬싱키',   country:'핀란드',   region:'유럽',     flag:'🇫🇮', tier:'high',aliases:['Helsinki']},
  {key:'reykjavik', name:'레이캬비크',country:'아이슬란드',region:'유럽',   flag:'🇮🇸', tier:'high',aliases:['Reykjavik','Reykjavík']},
  {key:'dublin',    name:'더블린',   country:'아일랜드', region:'유럽',     flag:'🇮🇪', tier:'mid', aliases:['Dublin']},
  {key:'athens',    name:'아테네',   country:'그리스',   region:'유럽',     flag:'🇬🇷', tier:'mid', aliases:['Athens']},
  {key:'santorini', name:'산토리니', country:'그리스',   region:'유럽',     flag:'🇬🇷', tier:'high',aliases:['Santorini']},
  {key:'istanbul',  name:'이스탄불', country:'튀르키예', region:'유럽',     flag:'🇹🇷', tier:'low', aliases:['Istanbul','İstanbul']},

  // 북미
  {key:'nyc',       name:'뉴욕',     country:'미국',     region:'북미',     flag:'🇺🇸', tier:'high',aliases:['New York','NYC','뉴욕']},
  {key:'la',        name:'로스앤젤레스',country:'미국',  region:'북미',     flag:'🇺🇸', tier:'high',aliases:['Los Angeles','LA']},
  {key:'sf',        name:'샌프란시스코',country:'미국',  region:'북미',     flag:'🇺🇸', tier:'high',aliases:['San Francisco','SF']},
  {key:'lasvegas',  name:'라스베이거스',country:'미국',  region:'북미',     flag:'🇺🇸', tier:'mid', aliases:['Las Vegas']},
  {key:'chicago',   name:'시카고',   country:'미국',     region:'북미',     flag:'🇺🇸', tier:'mid', aliases:['Chicago']},
  {key:'seattle',   name:'시애틀',   country:'미국',     region:'북미',     flag:'🇺🇸', tier:'mid', aliases:['Seattle']},
  {key:'honolulu',  name:'호놀룰루', country:'미국',     region:'북미',     flag:'🇺🇸', tier:'high',aliases:['Honolulu','Hawaii','하와이']},
  {key:'toronto',   name:'토론토',   country:'캐나다',   region:'북미',     flag:'🇨🇦', tier:'mid', aliases:['Toronto']},
  {key:'vancouver', name:'밴쿠버',   country:'캐나다',   region:'북미',     flag:'🇨🇦', tier:'mid', aliases:['Vancouver']},
  {key:'mexicocity',name:'멕시코시티',country:'멕시코',  region:'북미',     flag:'🇲🇽', tier:'low', aliases:['Mexico City','CDMX']},
  {key:'cancun',    name:'칸쿤',     country:'멕시코',   region:'북미',     flag:'🇲🇽', tier:'mid', aliases:['Cancun','Cancún']},

  // 중남미
  {key:'havana',    name:'아바나',   country:'쿠바',     region:'중남미',   flag:'🇨🇺', tier:'low', aliases:['Havana','Habana']},
  {key:'rio',       name:'리우',     country:'브라질',   region:'중남미',   flag:'🇧🇷', tier:'mid', aliases:['Rio de Janeiro']},
  {key:'saopaulo',  name:'상파울루', country:'브라질',   region:'중남미',   flag:'🇧🇷', tier:'mid', aliases:['São Paulo','Sao Paulo']},
  {key:'buenosaires',name:'부에노스아이레스',country:'아르헨티나',region:'중남미',flag:'🇦🇷',tier:'low',aliases:['Buenos Aires']},
  {key:'cusco',     name:'쿠스코',   country:'페루',     region:'중남미',   flag:'🇵🇪', tier:'low', aliases:['Cusco','Machu Picchu','마추픽추']},

  // 오세아니아
  {key:'sydney',    name:'시드니',   country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'high',aliases:['Sydney']},
  {key:'melbourne', name:'멜버른',   country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid', aliases:['Melbourne']},
  {key:'brisbane',  name:'브리즈번', country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid', aliases:['Brisbane']},
  {key:'goldcoast', name:'골드코스트',country:'호주',    region:'오세아니아',flag:'🇦🇺',tier:'mid', aliases:['Gold Coast']},
  {key:'auckland',  name:'오클랜드', country:'뉴질랜드', region:'오세아니아',flag:'🇳🇿',tier:'mid', aliases:['Auckland']},
  {key:'queenstown',name:'퀸스타운', country:'뉴질랜드', region:'오세아니아',flag:'🇳🇿',tier:'high',aliases:['Queenstown']},
  {key:'fiji',      name:'피지',     country:'피지',     region:'오세아니아',flag:'🇫🇯',tier:'mid', aliases:['Fiji','Nadi']},
  {key:'guam',      name:'괌',       country:'괌',       region:'오세아니아',flag:'🇬🇺',tier:'mid', aliases:['Guam']},
  {key:'saipan',    name:'사이판',   country:'북마리아나',region:'오세아니아',flag:'🇲🇵',tier:'mid', aliases:['Saipan']},

  // 중동 / 아프리카
  {key:'dubai',     name:'두바이',   country:'UAE',      region:'중동',     flag:'🇦🇪', tier:'high',aliases:['Dubai']},
  {key:'abudhabi',  name:'아부다비', country:'UAE',      region:'중동',     flag:'🇦🇪', tier:'high',aliases:['Abu Dhabi']},
  {key:'doha',      name:'도하',     country:'카타르',   region:'중동',     flag:'🇶🇦', tier:'high',aliases:['Doha']},
  {key:'cairo',     name:'카이로',   country:'이집트',   region:'아프리카', flag:'🇪🇬', tier:'low', aliases:['Cairo']},
  {key:'capetown',  name:'케이프타운',country:'남아공',  region:'아프리카', flag:'🇿🇦', tier:'mid', aliases:['Cape Town']},
  {key:'marrakech', name:'마라케시', country:'모로코',   region:'아프리카', flag:'🇲🇦', tier:'low', aliases:['Marrakech','Marrakesh']},

  // ─── 한국 소도시 / 관광지 ────────────────────────────────────────
  {key:'incheon',     name:'인천',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Incheon']},
  {key:'daegu',       name:'대구',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Daegu','Taegu']},
  {key:'daejeon',     name:'대전',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Daejeon']},
  {key:'gwangju',     name:'광주',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Gwangju']},
  {key:'ulsan',       name:'울산',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Ulsan']},
  {key:'suwon',       name:'수원',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Suwon']},
  {key:'chuncheon',   name:'춘천',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Chuncheon']},
  {key:'andong',      name:'안동',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Andong','하회마을']},
  {key:'pohang',      name:'포항',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Pohang']},
  {key:'tongyeong',   name:'통영',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Tongyeong']},
  {key:'geoje',       name:'거제',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Geoje']},
  {key:'namhae',      name:'남해',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Namhae']},
  {key:'cheongju',    name:'청주',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'mid', aliases:['Cheongju']},
  {key:'danyang',     name:'단양',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Danyang']},
  {key:'chungju',     name:'충주',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Chungju']},
  {key:'yangyang',    name:'양양',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Yangyang','서피비치']},
  {key:'pyeongchang', name:'평창',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Pyeongchang']},
  {key:'jeongseon',   name:'정선',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Jeongseon']},
  {key:'donghae',     name:'동해',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Donghae']},
  {key:'samcheok',    name:'삼척',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Samcheok']},
  {key:'gunsan',      name:'군산',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Gunsan']},
  {key:'iksan',       name:'익산',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Iksan']},
  {key:'buyeo',       name:'부여',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Buyeo']},
  {key:'gongju',      name:'공주',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Gongju']},
  {key:'boryeong',    name:'보령',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Boryeong','대천']},
  {key:'taean',       name:'태안',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Taean']},
  {key:'seosan',      name:'서산',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Seosan']},
  {key:'gapyeong',    name:'가평',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Gapyeong','남이섬']},
  {key:'yangpyeong',  name:'양평',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Yangpyeong']},
  {key:'ganghwa',     name:'강화',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Ganghwa']},
  {key:'mokpo',       name:'목포',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Mokpo']},
  {key:'damyang',     name:'담양',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Damyang']},
  {key:'suncheon',    name:'순천',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Suncheon','순천만']},
  {key:'goesan',      name:'괴산',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Goesan']},
  {key:'ulleung',     name:'울릉도',   country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Ulleungdo','독도']},
  {key:'inje',        name:'인제',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Inje']},
  {key:'hongcheon',   name:'홍천',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Hongcheon']},

  // ─── 일본 소도시 / 료칸 ─────────────────────────────────────────
  {key:'nara',        name:'나라',     country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Nara','奈良']},
  {key:'kobe',        name:'고베',     country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Kobe','神戸']},
  {key:'kanazawa',    name:'가나자와', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Kanazawa','金沢']},
  {key:'nikko',       name:'닛코',     country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Nikko','日光']},
  {key:'hakone',      name:'하코네',   country:'일본',     region:'아시아', flag:'🇯🇵', tier:'high',aliases:['Hakone','箱根']},
  {key:'kamakura',    name:'가마쿠라', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Kamakura','鎌倉']},
  {key:'takayama',    name:'다카야마', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Takayama','高山']},
  {key:'shirakawago', name:'시라카와고',country:'일본',    region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Shirakawago','白川郷']},
  {key:'matsumoto',   name:'마쓰모토', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Matsumoto','松本']},
  {key:'toyama',      name:'도야마',   country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Toyama','富山']},
  {key:'kagoshima',   name:'가고시마', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Kagoshima','鹿児島']},
  {key:'kumamoto',    name:'구마모토', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Kumamoto','熊本']},
  {key:'beppu',       name:'벳푸',     country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Beppu','別府']},
  {key:'yufuin',      name:'유후인',   country:'일본',     region:'아시아', flag:'🇯🇵', tier:'high',aliases:['Yufuin','由布院']},
  {key:'miyazaki',    name:'미야자키', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Miyazaki','宮崎']},
  {key:'sendai',      name:'센다이',   country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Sendai','仙台']},
  {key:'aomori',      name:'아오모리', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Aomori','青森']},
  {key:'hakodate',    name:'하코다테', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Hakodate','函館']},
  {key:'otaru',       name:'오타루',   country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Otaru','小樽']},
  {key:'noboribetsu', name:'노보리베쓰',country:'일본',   region:'아시아', flag:'🇯🇵', tier:'high',aliases:['Noboribetsu','登別']},
  {key:'shizuoka',    name:'시즈오카', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Shizuoka','静岡','후지산']},
  {key:'matsuyama',   name:'마쓰야마', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Matsuyama','松山']},
  {key:'takamatsu',   name:'다카마쓰', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Takamatsu','高松']},
  {key:'ishigaki',    name:'이시가키', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Ishigaki','石垣']},
  {key:'miyakojima',  name:'미야코지마',country:'일본',   region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Miyakojima','宮古島']},

  // ─── 동남아 비치/소도시 ─────────────────────────────────────────
  {key:'hoian',       name:'호이안',   country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Hoi An']},
  {key:'nhatrang',    name:'나트랑',   country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Nha Trang']},
  {key:'phuquoc',     name:'푸꾸옥',   country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Phu Quoc']},
  {key:'dalat',       name:'달랏',     country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Da Lat','Dalat']},
  {key:'sapa',        name:'사파',     country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Sa Pa']},
  {key:'kohsamui',    name:'코사무이', country:'태국',     region:'동남아', flag:'🇹🇭', tier:'mid', aliases:['Koh Samui']},
  {key:'krabi',       name:'끄라비',   country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Krabi']},
  {key:'pattaya',     name:'파타야',   country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Pattaya']},
  {key:'huahin',      name:'후아힌',   country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Hua Hin']},
  {key:'pai',         name:'빠이',     country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Pai']},
  {key:'penang',      name:'페낭',     country:'말레이시아',region:'동남아',flag:'🇲🇾', tier:'low', aliases:['Penang','Georgetown']},
  {key:'kotakinabalu',name:'코타키나발루',country:'말레이시아',region:'동남아',flag:'🇲🇾',tier:'low',aliases:['Kota Kinabalu','KK']},
  {key:'langkawi',    name:'랑카위',   country:'말레이시아',region:'동남아',flag:'🇲🇾', tier:'low', aliases:['Langkawi']},
  {key:'boracay',     name:'보라카이', country:'필리핀',   region:'동남아', flag:'🇵🇭', tier:'mid', aliases:['Boracay']},
  {key:'palawan',     name:'팔라완',   country:'필리핀',   region:'동남아', flag:'🇵🇭', tier:'mid', aliases:['Palawan','El Nido']},
  {key:'yogyakarta',  name:'족자카르타',country:'인도네시아',region:'동남아',flag:'🇮🇩', tier:'low', aliases:['Yogyakarta','Jogja']},
  {key:'lombok',      name:'롬복',     country:'인도네시아',region:'동남아',flag:'🇮🇩', tier:'mid', aliases:['Lombok']},
  {key:'batam',       name:'바탐',     country:'인도네시아',region:'동남아',flag:'🇮🇩', tier:'low', aliases:['Batam']},
  {key:'vientiane',   name:'비엔티안', country:'라오스',   region:'동남아', flag:'🇱🇦', tier:'low', aliases:['Vientiane']},
  {key:'luangprabang',name:'루앙프라방',country:'라오스',  region:'동남아', flag:'🇱🇦', tier:'low', aliases:['Luang Prabang']},
  {key:'yangon',      name:'양곤',     country:'미얀마',   region:'동남아', flag:'🇲🇲', tier:'low', aliases:['Yangon','Rangoon']},
  {key:'bagan',       name:'바간',     country:'미얀마',   region:'동남아', flag:'🇲🇲', tier:'low', aliases:['Bagan']},

  // ─── 남아시아 ───────────────────────────────────────────────────
  {key:'jaipur',      name:'자이푸르', country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Jaipur']},
  {key:'agra',        name:'아그라',   country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Agra','타지마할']},
  {key:'varanasi',    name:'바라나시', country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Varanasi','Benares']},
  {key:'goa',         name:'고아',     country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Goa']},
  {key:'galle',       name:'골',       country:'스리랑카', region:'남아시아',flag:'🇱🇰', tier:'low', aliases:['Galle']},
  {key:'pokhara',     name:'포카라',   country:'네팔',     region:'남아시아',flag:'🇳🇵', tier:'low', aliases:['Pokhara']},
  {key:'thimphu',     name:'팀부',     country:'부탄',     region:'남아시아',flag:'🇧🇹', tier:'mid', aliases:['Thimphu']},
  {key:'male',        name:'말레',     country:'몰디브',   region:'남아시아',flag:'🇲🇻', tier:'high',aliases:['Male','Maldives','몰디브']},

  // ─── 유럽 — 동/중유럽 ──────────────────────────────────────────
  {key:'salzburg',    name:'잘츠부르크',country:'오스트리아',region:'유럽', flag:'🇦🇹', tier:'mid', aliases:['Salzburg']},
  {key:'hallstatt',   name:'할슈타트', country:'오스트리아',region:'유럽', flag:'🇦🇹', tier:'mid', aliases:['Hallstatt']},
  {key:'innsbruck',   name:'인스브루크',country:'오스트리아',region:'유럽',flag:'🇦🇹', tier:'mid', aliases:['Innsbruck']},
  {key:'bruges',      name:'브뤼헤',   country:'벨기에',   region:'유럽',  flag:'🇧🇪', tier:'mid', aliases:['Bruges','Brugge']},
  {key:'antwerp',     name:'안트베르펜',country:'벨기에',  region:'유럽',  flag:'🇧🇪', tier:'mid', aliases:['Antwerp','Antwerpen']},
  {key:'luxembourg',  name:'룩셈부르크',country:'룩셈부르크',region:'유럽',flag:'🇱🇺', tier:'high',aliases:['Luxembourg']},
  {key:'monaco',      name:'모나코',   country:'모나코',   region:'유럽',  flag:'🇲🇨', tier:'high',aliases:['Monaco','Monte Carlo']},
  {key:'tallinn',     name:'탈린',     country:'에스토니아',region:'유럽', flag:'🇪🇪', tier:'low', aliases:['Tallinn']},
  {key:'riga',        name:'리가',     country:'라트비아', region:'유럽',  flag:'🇱🇻', tier:'low', aliases:['Riga']},
  {key:'vilnius',     name:'빌뉴스',   country:'리투아니아',region:'유럽', flag:'🇱🇹', tier:'low', aliases:['Vilnius']},
  {key:'dubrovnik',   name:'두브로브니크',country:'크로아티아',region:'유럽',flag:'🇭🇷',tier:'mid', aliases:['Dubrovnik']},
  {key:'split',       name:'스플리트', country:'크로아티아',region:'유럽', flag:'🇭🇷', tier:'mid', aliases:['Split']},
  {key:'zagreb',      name:'자그레브', country:'크로아티아',region:'유럽', flag:'🇭🇷', tier:'low', aliases:['Zagreb']},
  {key:'ljubljana',   name:'류블랴나', country:'슬로베니아',region:'유럽', flag:'🇸🇮', tier:'low', aliases:['Ljubljana']},
  {key:'bled',        name:'블레드',   country:'슬로베니아',region:'유럽', flag:'🇸🇮', tier:'mid', aliases:['Bled','Lake Bled']},
  {key:'krakow',      name:'크라쿠프', country:'폴란드',   region:'유럽',  flag:'🇵🇱', tier:'low', aliases:['Krakow','Kraków']},
  {key:'gdansk',      name:'그단스크', country:'폴란드',   region:'유럽',  flag:'🇵🇱', tier:'low', aliases:['Gdansk','Gdańsk']},
  {key:'bucharest',   name:'부쿠레슈티',country:'루마니아', region:'유럽',  flag:'🇷🇴', tier:'low', aliases:['Bucharest']},
  {key:'sofia',       name:'소피아',   country:'불가리아', region:'유럽',  flag:'🇧🇬', tier:'low', aliases:['Sofia']},

  // ─── 유럽 — 서/남유럽 소도시 ────────────────────────────────────
  {key:'cannes',      name:'칸',       country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'high',aliases:['Cannes']},
  {key:'lyon',        name:'리옹',     country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Lyon']},
  {key:'marseille',   name:'마르세유', country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Marseille']},
  {key:'bordeaux',    name:'보르도',   country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Bordeaux']},
  {key:'strasbourg',  name:'스트라스부르',country:'프랑스',region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Strasbourg']},
  {key:'avignon',     name:'아비뇽',   country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Avignon']},
  {key:'oxford',      name:'옥스퍼드', country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Oxford']},
  {key:'cambridge',   name:'케임브리지',country:'영국',    region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Cambridge']},
  {key:'bath',        name:'바스',     country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Bath']},
  {key:'manchester',  name:'맨체스터', country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Manchester']},
  {key:'glasgow',     name:'글래스고', country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Glasgow']},
  {key:'liverpool',   name:'리버풀',   country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Liverpool']},
  {key:'naples',      name:'나폴리',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Naples','Napoli']},
  {key:'verona',      name:'베로나',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Verona']},
  {key:'siena',       name:'시에나',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Siena']},
  {key:'pisa',        name:'피사',     country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Pisa']},
  {key:'bologna',     name:'볼로냐',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Bologna']},
  {key:'turin',       name:'토리노',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Turin','Torino']},
  {key:'como',        name:'코모',     country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'high',aliases:['Como','Lake Como']},
  {key:'cinqueterre', name:'친퀘테레', country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'high',aliases:['Cinque Terre']},
  {key:'positano',    name:'포지타노', country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'high',aliases:['Positano']},
  {key:'amalfi',      name:'아말피',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'high',aliases:['Amalfi']},
  {key:'seville',     name:'세비야',   country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Seville','Sevilla']},
  {key:'granada',     name:'그라나다', country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Granada','Alhambra']},
  {key:'valencia',    name:'발렌시아', country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Valencia']},
  {key:'bilbao',      name:'빌바오',   country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Bilbao']},
  {key:'sansebastian',name:'산세바스티안',country:'스페인',region:'유럽', flag:'🇪🇸', tier:'mid', aliases:['San Sebastian','Donostia']},
  {key:'toledo',      name:'톨레도',   country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Toledo']},
  {key:'cordoba',     name:'코르도바', country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Cordoba','Córdoba']},
  {key:'sintra',      name:'신트라',   country:'포르투갈', region:'유럽',  flag:'🇵🇹', tier:'mid', aliases:['Sintra']},
  {key:'madeira',     name:'마데이라', country:'포르투갈', region:'유럽',  flag:'🇵🇹', tier:'mid', aliases:['Madeira','Funchal']},
  {key:'hamburg',     name:'함부르크', country:'독일',     region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Hamburg']},
  {key:'cologne',     name:'쾰른',     country:'독일',     region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Cologne','Köln']},
  {key:'heidelberg',  name:'하이델베르크',country:'독일', region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Heidelberg']},
  {key:'rothenburg',  name:'로텐부르크',country:'독일',  region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Rothenburg','Rothenburg ob der Tauber']},
  {key:'dresden',     name:'드레스덴', country:'독일',     region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Dresden']},
  {key:'nuremberg',   name:'뉘른베르크',country:'독일',  region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Nuremberg','Nürnberg']},
  {key:'lucerne',     name:'루체른',   country:'스위스',   region:'유럽',  flag:'🇨🇭', tier:'high',aliases:['Lucerne','Luzern']},
  {key:'geneva',      name:'제네바',   country:'스위스',   region:'유럽',  flag:'🇨🇭', tier:'high',aliases:['Geneva','Genève']},
  {key:'bergen',      name:'베르겐',   country:'노르웨이', region:'유럽',  flag:'🇳🇴', tier:'high',aliases:['Bergen']},
  {key:'tromso',      name:'트롬쇠',   country:'노르웨이', region:'유럽',  flag:'🇳🇴', tier:'high',aliases:['Tromso','Tromsø','오로라']},
  {key:'rovaniemi',   name:'로바니에미',country:'핀란드', region:'유럽',  flag:'🇫🇮', tier:'high',aliases:['Rovaniemi','산타마을','라플란드']},
  {key:'galway',      name:'골웨이',   country:'아일랜드', region:'유럽',  flag:'🇮🇪', tier:'mid', aliases:['Galway']},
  {key:'mykonos',     name:'미코노스', country:'그리스',   region:'유럽',  flag:'🇬🇷', tier:'high',aliases:['Mykonos']},
  {key:'crete',       name:'크레타',   country:'그리스',   region:'유럽',  flag:'🇬🇷', tier:'mid', aliases:['Crete','Heraklion']},
  {key:'corfu',       name:'코르푸',   country:'그리스',   region:'유럽',  flag:'🇬🇷', tier:'mid', aliases:['Corfu']},
  {key:'cappadocia',  name:'카파도키아',country:'튀르키예',region:'유럽',  flag:'🇹🇷', tier:'low', aliases:['Cappadocia','Goreme']},
  {key:'antalya',     name:'안탈리아', country:'튀르키예', region:'유럽',  flag:'🇹🇷', tier:'low', aliases:['Antalya']},

  // ─── 북미 — 미국/캐나다 소도시 ─────────────────────────────────
  {key:'boston',      name:'보스턴',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Boston']},
  {key:'miami',       name:'마이애미', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Miami']},
  {key:'orlando',     name:'올랜도',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Orlando','디즈니월드']},
  {key:'washington',  name:'워싱턴DC', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Washington','Washington DC','DC']},
  {key:'sandiego',    name:'샌디에이고',country:'미국',   region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['San Diego']},
  {key:'portland',    name:'포틀랜드', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Portland']},
  {key:'denver',      name:'덴버',     country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Denver']},
  {key:'austin',      name:'오스틴',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Austin']},
  {key:'neworleans',  name:'뉴올리언스',country:'미국',   region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['New Orleans','NOLA']},
  {key:'nashville',   name:'내슈빌',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Nashville']},
  {key:'philadelphia',name:'필라델피아',country:'미국',   region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Philadelphia','Philly']},
  {key:'maui',        name:'마우이',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Maui']},
  {key:'keywest',     name:'키웨스트', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Key West']},
  {key:'montreal',    name:'몬트리올', country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'mid', aliases:['Montreal','Montréal']},
  {key:'quebec',      name:'퀘벡',     country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'mid', aliases:['Quebec','Quebec City']},
  {key:'calgary',     name:'캘거리',   country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'mid', aliases:['Calgary','Banff']},
  {key:'whistler',    name:'휘슬러',   country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'high',aliases:['Whistler']},
  {key:'ottawa',      name:'오타와',   country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'mid', aliases:['Ottawa']},
  {key:'playadelcarmen',name:'플라야델카르멘',country:'멕시코',region:'북미',flag:'🇲🇽',tier:'mid',aliases:['Playa del Carmen']},
  {key:'tulum',       name:'툴룸',     country:'멕시코',   region:'북미',  flag:'🇲🇽', tier:'mid', aliases:['Tulum']},
  {key:'oaxaca',      name:'오악사카', country:'멕시코',   region:'북미',  flag:'🇲🇽', tier:'low', aliases:['Oaxaca']},

  // ─── 중남미 ─────────────────────────────────────────────────────
  {key:'cartagena',   name:'카르타헤나',country:'콜롬비아',region:'중남미',flag:'🇨🇴', tier:'low', aliases:['Cartagena']},
  {key:'medellin',    name:'메데인',   country:'콜롬비아', region:'중남미',flag:'🇨🇴', tier:'low', aliases:['Medellin','Medellín']},
  {key:'quito',       name:'키토',     country:'에콰도르', region:'중남미',flag:'🇪🇨', tier:'low', aliases:['Quito']},
  {key:'galapagos',   name:'갈라파고스',country:'에콰도르',region:'중남미',flag:'🇪🇨', tier:'high',aliases:['Galapagos','Galápagos']},
  {key:'santiagocl',  name:'산티아고', country:'칠레',     region:'중남미',flag:'🇨🇱', tier:'mid', aliases:['Santiago']},
  {key:'valparaiso',  name:'발파라이소',country:'칠레',   region:'중남미',flag:'🇨🇱', tier:'low', aliases:['Valparaiso','Valparaíso']},
  {key:'iguazu',      name:'이구아수', country:'브라질',   region:'중남미',flag:'🇧🇷', tier:'mid', aliases:['Iguazu','Foz do Iguacu']},
  {key:'salvador',    name:'살바도르', country:'브라질',   region:'중남미',flag:'🇧🇷', tier:'low', aliases:['Salvador']},
  {key:'mendoza',     name:'멘도사',   country:'아르헨티나',region:'중남미',flag:'🇦🇷',tier:'low', aliases:['Mendoza']},
  {key:'ushuaia',     name:'우슈아이아',country:'아르헨티나',region:'중남미',flag:'🇦🇷',tier:'mid', aliases:['Ushuaia']},
  {key:'sanjose',     name:'산호세',   country:'코스타리카',region:'중남미',flag:'🇨🇷',tier:'mid', aliases:['San Jose','San José']},

  // ─── 오세아니아 ─────────────────────────────────────────────────
  {key:'cairns',      name:'케언스',   country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid',aliases:['Cairns','그레이트배리어리프']},
  {key:'darwin',      name:'다윈',     country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid',aliases:['Darwin']},
  {key:'hobart',      name:'호바트',   country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid',aliases:['Hobart','Tasmania']},
  {key:'adelaide',    name:'애들레이드',country:'호주',   region:'오세아니아',flag:'🇦🇺',tier:'mid',aliases:['Adelaide']},
  {key:'perth',       name:'퍼스',     country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid',aliases:['Perth']},
  {key:'canberra',    name:'캔버라',   country:'호주',     region:'오세아니아',flag:'🇦🇺',tier:'mid',aliases:['Canberra']},
  {key:'wellington',  name:'웰링턴',   country:'뉴질랜드', region:'오세아니아',flag:'🇳🇿',tier:'mid',aliases:['Wellington']},
  {key:'christchurch',name:'크라이스트처치',country:'뉴질랜드',region:'오세아니아',flag:'🇳🇿',tier:'mid',aliases:['Christchurch']},
  {key:'rotorua',     name:'로토루아', country:'뉴질랜드', region:'오세아니아',flag:'🇳🇿',tier:'mid',aliases:['Rotorua']},
  {key:'tahiti',      name:'타히티',   country:'프랑스령폴리네시아',region:'오세아니아',flag:'🇵🇫',tier:'high',aliases:['Tahiti','Bora Bora','보라보라']},
  {key:'newcaledonia',name:'누벨칼레도니',country:'뉴칼레도니',region:'오세아니아',flag:'🇳🇨',tier:'high',aliases:['New Caledonia','Noumea','누메아']},
  {key:'palau',       name:'팔라우',   country:'팔라우',   region:'오세아니아',flag:'🇵🇼',tier:'high',aliases:['Palau']},

  // ─── 중동 / 아프리카 ────────────────────────────────────────────
  {key:'telaviv',     name:'텔아비브', country:'이스라엘', region:'중동',  flag:'🇮🇱', tier:'high',aliases:['Tel Aviv']},
  {key:'jerusalem',   name:'예루살렘', country:'이스라엘', region:'중동',  flag:'🇮🇱', tier:'mid', aliases:['Jerusalem']},
  {key:'petra',       name:'페트라',   country:'요르단',   region:'중동',  flag:'🇯🇴', tier:'mid', aliases:['Petra','Wadi Musa']},
  {key:'amman',       name:'암만',     country:'요르단',   region:'중동',  flag:'🇯🇴', tier:'mid', aliases:['Amman']},
  {key:'muscat',      name:'무스카트', country:'오만',     region:'중동',  flag:'🇴🇲', tier:'mid', aliases:['Muscat']},
  {key:'beirut',      name:'베이루트', country:'레바논',   region:'중동',  flag:'🇱🇧', tier:'low', aliases:['Beirut']},
  {key:'nairobi',     name:'나이로비', country:'케냐',     region:'아프리카',flag:'🇰🇪', tier:'low', aliases:['Nairobi']},
  {key:'zanzibar',    name:'잔지바르', country:'탄자니아', region:'아프리카',flag:'🇹🇿', tier:'mid', aliases:['Zanzibar','Stone Town']},
  {key:'victoriafalls',name:'빅토리아폭포',country:'잠비아',region:'아프리카',flag:'🇿🇲',tier:'mid',aliases:['Victoria Falls','Livingstone']},
  {key:'mauritius',   name:'모리셔스', country:'모리셔스', region:'아프리카',flag:'🇲🇺', tier:'high',aliases:['Mauritius','Port Louis']},
  {key:'seychelles',  name:'세이셸',   country:'세이셸',   region:'아프리카',flag:'🇸🇨', tier:'high',aliases:['Seychelles','Victoria']},

  // ─── 중국 대량 추가 ────────────────────────────────────────────
  {key:'hangzhou',    name:'항저우',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Hangzhou','杭州','항주']},
  {key:'guangzhou',   name:'광저우',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Guangzhou','广州','광주(중국)']},
  {key:'shenzhen',    name:'선전',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Shenzhen','深圳','심천']},
  {key:'suzhou',      name:'쑤저우',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Suzhou','苏州','소주']},
  {key:'xian',        name:'시안',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Xian',"Xi'an",'西安','서안','병마용']},
  {key:'chongqing',   name:'충칭',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Chongqing','重庆','중경']},
  {key:'tianjin',     name:'톈진',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Tianjin','天津','천진']},
  {key:'wuhan',       name:'우한',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Wuhan','武汉']},
  {key:'qingdao',     name:'칭다오',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Qingdao','青岛','청도']},
  {key:'dalian',      name:'다롄',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Dalian','大连','대련']},
  {key:'harbin',      name:'하얼빈',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Harbin','哈尔滨']},
  {key:'sanya',       name:'산야',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Sanya','三亚','하이난']},
  {key:'guilin',      name:'구이린',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Guilin','桂林','계림']},
  {key:'lijiang',     name:'리장',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Lijiang','丽江','여강']},
  {key:'kunming',     name:'쿤밍',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Kunming','昆明','곤명']},
  {key:'dali',        name:'다리',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Dali','大理']},
  {key:'zhangjiajie', name:'장가계',   country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Zhangjiajie','张家界']},
  {key:'huangshan',   name:'황산',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Huangshan','黄山']},
  {key:'nanjing',     name:'난징',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Nanjing','南京','남경']},
  {key:'lhasa',       name:'라싸',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Lhasa','拉萨','티베트']},
  {key:'urumqi',      name:'우루무치', country:'중국',     region:'아시아', flag:'🇨🇳', tier:'low', aliases:['Urumqi','乌鲁木齐']},
  {key:'xiamen',      name:'샤먼',     country:'중국',     region:'아시아', flag:'🇨🇳', tier:'mid', aliases:['Xiamen','厦门','하문']},

  // ─── 한국 추가 (남부·도서·관광지) ────────────────────────────
  {key:'jinju',       name:'진주',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Jinju']},
  {key:'gimhae',      name:'김해',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Gimhae']},
  {key:'jinhae',      name:'진해',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Jinhae','벚꽃']},
  {key:'sacheon',     name:'사천',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Sacheon']},
  {key:'hadong',      name:'하동',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Hadong']},
  {key:'gwangyang',   name:'광양',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Gwangyang']},
  {key:'boseong',     name:'보성',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Boseong','녹차밭']},
  {key:'haenam',      name:'해남',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Haenam','땅끝마을']},
  {key:'wando',       name:'완도',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Wando','청산도']},
  {key:'jindo',       name:'진도',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Jindo']},
  {key:'sinan',       name:'신안',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Sinan','홍도','흑산도']},
  {key:'namwon',      name:'남원',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Namwon','지리산']},
  {key:'jeongeup',    name:'정읍',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Jeongeup','내장산']},
  {key:'buan',        name:'부안',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Buan','변산']},
  {key:'jecheon',     name:'제천',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Jecheon']},
  {key:'yeongwol',    name:'영월',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Yeongwol']},
  {key:'taebaek',     name:'태백',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Taebaek']},
  {key:'yeongdeok',   name:'영덕',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Yeongdeok','대게']},
  {key:'uljin',       name:'울진',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Uljin']},
  {key:'yeongju',     name:'영주',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Yeongju','부석사']},
  {key:'goseong-gw',  name:'고성',     country:'대한민국', region:'아시아', flag:'🇰🇷', tier:'low', aliases:['Goseong','강원고성']},

  // ─── 일본 추가 (관광지·온천) ────────────────────────────────
  {key:'fujikawaguchiko', name:'후지카와구치코',country:'일본',region:'아시아',flag:'🇯🇵',tier:'mid',aliases:['Fujikawaguchiko','후지5호','Kawaguchi']},
  {key:'karuizawa',   name:'가루이자와',country:'일본',    region:'아시아', flag:'🇯🇵', tier:'high',aliases:['Karuizawa','軽井沢']},
  {key:'miyajima',    name:'미야지마', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Miyajima','宮島','이쓰쿠시마']},
  {key:'yakushima',   name:'야쿠시마', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Yakushima','屋久島']},
  {key:'izu',         name:'이즈',     country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Izu','伊豆']},
  {key:'oita',        name:'오이타',   country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Oita','大分']},
  {key:'kurashiki',   name:'구라시키', country:'일본',     region:'아시아', flag:'🇯🇵', tier:'mid', aliases:['Kurashiki','倉敷']},

  // ─── 동남아 추가 ────────────────────────────────────────────
  {key:'hue',         name:'후에',     country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Hue','Huế']},
  {key:'muine',       name:'무이네',   country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Mui Ne']},
  {key:'halongbay',   name:'하롱베이', country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Halong Bay','Ha Long']},
  {key:'ninhbinh',    name:'닌빈',     country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Ninh Binh']},
  {key:'cantho',      name:'껀터',     country:'베트남',   region:'동남아', flag:'🇻🇳', tier:'low', aliases:['Can Tho','Cần Thơ']},
  {key:'ayutthaya',   name:'아유타야', country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Ayutthaya']},
  {key:'sukhothai',   name:'수코타이', country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Sukhothai']},
  {key:'kohtao',      name:'코타오',   country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Koh Tao']},
  {key:'kohphangan',  name:'코팡안',   country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Koh Phangan']},
  {key:'kohchang',    name:'코창',     country:'태국',     region:'동남아', flag:'🇹🇭', tier:'low', aliases:['Koh Chang']},
  {key:'phnompenh',   name:'프놈펜',   country:'캄보디아', region:'동남아', flag:'🇰🇭', tier:'low', aliases:['Phnom Penh']},
  {key:'sihanoukville',name:'시아누크빌',country:'캄보디아',region:'동남아',flag:'🇰🇭', tier:'low', aliases:['Sihanoukville']},
  {key:'mandalay',    name:'만달레이', country:'미얀마',   region:'동남아', flag:'🇲🇲', tier:'low', aliases:['Mandalay']},
  {key:'inlelake',    name:'인레호수', country:'미얀마',   region:'동남아', flag:'🇲🇲', tier:'low', aliases:['Inle Lake']},
  {key:'bohol',       name:'보홀',     country:'필리핀',   region:'동남아', flag:'🇵🇭', tier:'low', aliases:['Bohol']},
  {key:'davao',       name:'다바오',   country:'필리핀',   region:'동남아', flag:'🇵🇭', tier:'low', aliases:['Davao']},
  {key:'medan',       name:'메단',     country:'인도네시아',region:'동남아',flag:'🇮🇩', tier:'low', aliases:['Medan']},
  {key:'surabaya',    name:'수라바야', country:'인도네시아',region:'동남아',flag:'🇮🇩', tier:'low', aliases:['Surabaya']},
  {key:'bandung',     name:'반둥',     country:'인도네시아',region:'동남아',flag:'🇮🇩', tier:'low', aliases:['Bandung']},
  {key:'bruneicity',  name:'반다르스리브가완',country:'브루나이',region:'동남아',flag:'🇧🇳',tier:'mid',aliases:['Bandar Seri Begawan','Brunei']},

  // ─── 남아시아 추가 ──────────────────────────────────────────
  {key:'kolkata',     name:'콜카타',   country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Kolkata','Calcutta']},
  {key:'chennai',     name:'첸나이',   country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Chennai','Madras']},
  {key:'bangalore',   name:'벵갈루루', country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Bangalore','Bengaluru']},
  {key:'hyderabad',   name:'하이데라바드',country:'인도', region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Hyderabad']},
  {key:'pune',        name:'푸네',     country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Pune']},
  {key:'udaipur',     name:'우다이푸르',country:'인도',   region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Udaipur']},
  {key:'jodhpur',     name:'조드푸르', country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Jodhpur']},
  {key:'darjeeling',  name:'다르질링', country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Darjeeling']},
  {key:'kerala',      name:'케랄라',   country:'인도',     region:'남아시아',flag:'🇮🇳', tier:'low', aliases:['Kerala','Kochi','Cochin','코치']},
  {key:'paro',        name:'파로',     country:'부탄',     region:'남아시아',flag:'🇧🇹', tier:'mid', aliases:['Paro']},
  {key:'kandy',       name:'캔디',     country:'스리랑카', region:'남아시아',flag:'🇱🇰', tier:'low', aliases:['Kandy']},
  {key:'ella',        name:'엘라',     country:'스리랑카', region:'남아시아',flag:'🇱🇰', tier:'low', aliases:['Ella']},

  // ─── 중앙아시아 / 코카서스 (신규 지역) ──────────────────────
  {key:'almaty',      name:'알마티',   country:'카자흐스탄',region:'중앙아시아',flag:'🇰🇿',tier:'low',aliases:['Almaty','Алматы']},
  {key:'astana',      name:'아스타나', country:'카자흐스탄',region:'중앙아시아',flag:'🇰🇿',tier:'low',aliases:['Astana','Nur-Sultan']},
  {key:'tashkent',    name:'타슈켄트', country:'우즈베키스탄',region:'중앙아시아',flag:'🇺🇿',tier:'low',aliases:['Tashkent']},
  {key:'samarkand',   name:'사마르칸트',country:'우즈베키스탄',region:'중앙아시아',flag:'🇺🇿',tier:'low',aliases:['Samarkand']},
  {key:'bukhara',     name:'부하라',   country:'우즈베키스탄',region:'중앙아시아',flag:'🇺🇿',tier:'low',aliases:['Bukhara']},
  {key:'bishkek',     name:'비슈케크', country:'키르기스스탄',region:'중앙아시아',flag:'🇰🇬',tier:'low',aliases:['Bishkek']},
  {key:'ulaanbaatar', name:'울란바토르',country:'몽골',    region:'중앙아시아',flag:'🇲🇳',tier:'low',aliases:['Ulaanbaatar','Ulan Bator']},
  {key:'tbilisi',     name:'트빌리시', country:'조지아',   region:'중앙아시아',flag:'🇬🇪',tier:'low',aliases:['Tbilisi']},
  {key:'baku',        name:'바쿠',     country:'아제르바이잔',region:'중앙아시아',flag:'🇦🇿',tier:'mid',aliases:['Baku']},
  {key:'yerevan',     name:'예레반',   country:'아르메니아',region:'중앙아시아',flag:'🇦🇲',tier:'low',aliases:['Yerevan']},

  // ─── 미국 — 더 많은 도시 ───────────────────────────────────
  {key:'atlanta',     name:'애틀랜타', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Atlanta']},
  {key:'phoenix',     name:'피닉스',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Phoenix','Scottsdale']},
  {key:'houston',     name:'휴스턴',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Houston']},
  {key:'dallas',      name:'댈러스',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Dallas','Fort Worth']},
  {key:'detroit',     name:'디트로이트',country:'미국',   region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Detroit']},
  {key:'minneapolis', name:'미니애폴리스',country:'미국', region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Minneapolis','Twin Cities']},
  {key:'pittsburgh',  name:'피츠버그', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Pittsburgh']},
  {key:'kansascity',  name:'캔자스시티',country:'미국',   region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Kansas City']},
  {key:'stlouis',     name:'세인트루이스',country:'미국', region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['St Louis','St. Louis']},
  {key:'memphis',     name:'멤피스',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Memphis']},
  {key:'tampa',       name:'탬파',     country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Tampa']},
  {key:'charleston',  name:'찰스턴',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Charleston']},
  {key:'savannah',    name:'사바나',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Savannah']},
  {key:'saltlakecity',name:'솔트레이크시티',country:'미국',region:'북미',flag:'🇺🇸',tier:'mid',aliases:['Salt Lake City','SLC']},
  {key:'santafe',     name:'산타페',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Santa Fe']},
  {key:'sedona',      name:'세도나',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Sedona']},
  {key:'aspen',       name:'아스펜',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Aspen']},
  {key:'jacksonhole', name:'잭슨홀',   country:'미국',     region:'북미',  flag:'🇺🇸', tier:'high',aliases:['Jackson Hole','Yellowstone','옐로스톤']},
  {key:'anchorage',   name:'앵커리지', country:'미국',     region:'북미',  flag:'🇺🇸', tier:'mid', aliases:['Anchorage','Alaska','알래스카']},

  // ─── 캐나다 추가 ────────────────────────────────────────────
  {key:'halifax',     name:'핼리팩스', country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'mid', aliases:['Halifax']},
  {key:'victoria-ca', name:'빅토리아', country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'mid', aliases:['Victoria']},
  {key:'banff',       name:'밴프',     country:'캐나다',   region:'북미',  flag:'🇨🇦', tier:'high',aliases:['Banff','Lake Louise']},
  {key:'yellowknife', name:'옐로나이프',country:'캐나다', region:'북미',  flag:'🇨🇦', tier:'high',aliases:['Yellowknife','오로라']},

  // ─── 멕시코 추가 ────────────────────────────────────────────
  {key:'puertovallarta',name:'푸에르토바야르타',country:'멕시코',region:'북미',flag:'🇲🇽',tier:'mid',aliases:['Puerto Vallarta']},
  {key:'sanmiguel',   name:'산미겔데아옌데',country:'멕시코',region:'북미',flag:'🇲🇽', tier:'mid', aliases:['San Miguel de Allende']},
  {key:'merida',      name:'메리다',   country:'멕시코',   region:'북미',  flag:'🇲🇽', tier:'low', aliases:['Merida','Mérida']},

  // ─── 중남미 추가 ────────────────────────────────────────────
  {key:'bogota',      name:'보고타',   country:'콜롬비아', region:'중남미',flag:'🇨🇴', tier:'low', aliases:['Bogota','Bogotá']},
  {key:'lima',        name:'리마',     country:'페루',     region:'중남미',flag:'🇵🇪', tier:'low', aliases:['Lima']},
  {key:'arequipa',    name:'아레키파', country:'페루',     region:'중남미',flag:'🇵🇪', tier:'low', aliases:['Arequipa']},
  {key:'lapaz',       name:'라파스',   country:'볼리비아', region:'중남미',flag:'🇧🇴', tier:'low', aliases:['La Paz']},
  {key:'uyuni',       name:'우유니',   country:'볼리비아', region:'중남미',flag:'🇧🇴', tier:'low', aliases:['Uyuni','Salar de Uyuni','우유니소금사막']},
  {key:'salta',       name:'살타',     country:'아르헨티나',region:'중남미',flag:'🇦🇷',tier:'low', aliases:['Salta']},
  {key:'bariloche',   name:'바릴로체', country:'아르헨티나',region:'중남미',flag:'🇦🇷',tier:'mid', aliases:['Bariloche']},
  {key:'elcalafate',  name:'엘칼라파테',country:'아르헨티나',region:'중남미',flag:'🇦🇷',tier:'mid',aliases:['El Calafate','Perito Moreno']},
  {key:'easterisland',name:'이스터섬', country:'칠레',     region:'중남미',flag:'🇨🇱', tier:'high',aliases:['Easter Island','Rapa Nui','이스터아일랜드']},
  {key:'montevideo',  name:'몬테비데오',country:'우루과이',region:'중남미',flag:'🇺🇾', tier:'low', aliases:['Montevideo']},
  {key:'panamacity',  name:'파나마시티',country:'파나마', region:'중남미',flag:'🇵🇦', tier:'low', aliases:['Panama City']},
  {key:'antigua',     name:'안티과',   country:'과테말라', region:'중남미',flag:'🇬🇹', tier:'low', aliases:['Antigua','Antigua Guatemala']},

  // ─── 유럽 추가 — 동/북유럽 + 러시아 ─────────────────────────
  {key:'moscow',      name:'모스크바', country:'러시아',   region:'유럽',  flag:'🇷🇺', tier:'mid', aliases:['Moscow','Москва']},
  {key:'stpetersburg',name:'상트페테르부르크',country:'러시아',region:'유럽',flag:'🇷🇺',tier:'mid',aliases:['St Petersburg','Saint Petersburg','상트']},
  {key:'kyiv',        name:'키이우',   country:'우크라이나',region:'유럽', flag:'🇺🇦', tier:'low', aliases:['Kyiv','Kiev']},
  {key:'minsk',       name:'민스크',   country:'벨라루스', region:'유럽',  flag:'🇧🇾', tier:'low', aliases:['Minsk']},
  {key:'sarajevo',    name:'사라예보', country:'보스니아', region:'유럽',  flag:'🇧🇦', tier:'low', aliases:['Sarajevo']},
  {key:'mostar',      name:'모스타르', country:'보스니아', region:'유럽',  flag:'🇧🇦', tier:'low', aliases:['Mostar']},
  {key:'belgrade',    name:'베오그라드',country:'세르비아',region:'유럽',  flag:'🇷🇸', tier:'low', aliases:['Belgrade','Beograd']},
  {key:'skopje',      name:'스코페',   country:'북마케도니아',region:'유럽',flag:'🇲🇰',tier:'low',aliases:['Skopje']},
  {key:'tirana',      name:'티라나',   country:'알바니아', region:'유럽',  flag:'🇦🇱', tier:'low', aliases:['Tirana']},
  {key:'thessaloniki',name:'테살로니키',country:'그리스', region:'유럽',  flag:'🇬🇷', tier:'mid', aliases:['Thessaloniki']},
  {key:'rhodes',      name:'로도스',   country:'그리스',   region:'유럽',  flag:'🇬🇷', tier:'mid', aliases:['Rhodes','Rhodos']},
  {key:'malta',       name:'발레타',   country:'몰타',     region:'유럽',  flag:'🇲🇹', tier:'mid', aliases:['Malta','Valletta']},
  {key:'reykjavik2',  name:'레이캬비크2',country:'아이슬란드',region:'유럽',flag:'🇮🇸',tier:'high',aliases:['Vík','비크']},
  {key:'kaunas',      name:'카우나스', country:'리투아니아',region:'유럽', flag:'🇱🇹', tier:'low', aliases:['Kaunas']},
  {key:'aarhus',      name:'오르후스', country:'덴마크',   region:'유럽',  flag:'🇩🇰', tier:'high',aliases:['Aarhus','Århus']},
  {key:'malmo',       name:'말뫼',     country:'스웨덴',   region:'유럽',  flag:'🇸🇪', tier:'high',aliases:['Malmo','Malmö']},
  {key:'gothenburg',  name:'예테보리', country:'스웨덴',   region:'유럽',  flag:'🇸🇪', tier:'high',aliases:['Gothenburg','Göteborg']},
  {key:'tampere',     name:'탐페레',   country:'핀란드',   region:'유럽',  flag:'🇫🇮', tier:'high',aliases:['Tampere']},
  {key:'plovdiv',     name:'플로브디프',country:'불가리아',region:'유럽',  flag:'🇧🇬', tier:'low', aliases:['Plovdiv']},
  {key:'bratislava',  name:'브라티슬라바',country:'슬로바키아',region:'유럽',flag:'🇸🇰',tier:'low',aliases:['Bratislava']},

  // ─── 유럽 추가 — 서/남유럽 더 ─────────────────────────────
  {key:'biarritz',    name:'비아리츠', country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'high',aliases:['Biarritz']},
  {key:'tours',       name:'투르',     country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Tours','Loire']},
  {key:'reims',       name:'랭스',     country:'프랑스',   region:'유럽',  flag:'🇫🇷', tier:'mid', aliases:['Reims','Champagne','샹파뉴']},
  {key:'york',        name:'요크',     country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['York']},
  {key:'brighton',    name:'브라이튼', country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Brighton']},
  {key:'belfast',     name:'벨파스트', country:'영국',     region:'유럽',  flag:'🇬🇧', tier:'mid', aliases:['Belfast']},
  {key:'genoa',       name:'제노바',   country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Genoa','Genova']},
  {key:'palermo',     name:'팔레르모', country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Palermo','Sicily','시칠리아']},
  {key:'catania',     name:'카타니아', country:'이탈리아', region:'유럽',  flag:'🇮🇹', tier:'mid', aliases:['Catania']},
  {key:'malaga',      name:'말라가',   country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Malaga','Málaga','Costa del Sol']},
  {key:'palma',       name:'팔마',     country:'스페인',   region:'유럽',  flag:'🇪🇸', tier:'mid', aliases:['Palma','Mallorca','마요르카']},
  {key:'lagos',       name:'라고스',   country:'포르투갈', region:'유럽',  flag:'🇵🇹', tier:'mid', aliases:['Lagos','Algarve']},
  {key:'rotterdam',   name:'로테르담', country:'네덜란드', region:'유럽',  flag:'🇳🇱', tier:'high',aliases:['Rotterdam']},
  {key:'thehague',    name:'헤이그',   country:'네덜란드', region:'유럽',  flag:'🇳🇱', tier:'high',aliases:['The Hague','Den Haag']},
  {key:'bonn',        name:'본',       country:'독일',     region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Bonn']},
  {key:'stuttgart',   name:'슈투트가르트',country:'독일', region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Stuttgart']},
  {key:'leipzig',     name:'라이프치히',country:'독일',   region:'유럽',  flag:'🇩🇪', tier:'mid', aliases:['Leipzig']},
  {key:'basel',       name:'바젤',     country:'스위스',   region:'유럽',  flag:'🇨🇭', tier:'high',aliases:['Basel']},
  {key:'bern',        name:'베른',     country:'스위스',   region:'유럽',  flag:'🇨🇭', tier:'high',aliases:['Bern']},
  {key:'graz',        name:'그라츠',   country:'오스트리아',region:'유럽', flag:'🇦🇹', tier:'mid', aliases:['Graz']},

  // ─── 중동 / 아프리카 추가 ───────────────────────────────────
  {key:'riyadh',      name:'리야드',   country:'사우디아라비아',region:'중동',flag:'🇸🇦',tier:'mid',aliases:['Riyadh']},
  {key:'jeddah',      name:'제다',     country:'사우디아라비아',region:'중동',flag:'🇸🇦',tier:'mid',aliases:['Jeddah']},
  {key:'muscat-om',   name:'무스카트2',country:'오만',     region:'중동',  flag:'🇴🇲', tier:'mid', aliases:['Salalah','살랄라']},
  {key:'manama',      name:'마나마',   country:'바레인',   region:'중동',  flag:'🇧🇭', tier:'mid', aliases:['Manama']},
  {key:'kuwaitcity',  name:'쿠웨이트시티',country:'쿠웨이트',region:'중동',flag:'🇰🇼', tier:'mid', aliases:['Kuwait City']},
  {key:'tehran',      name:'테헤란',   country:'이란',     region:'중동',  flag:'🇮🇷', tier:'low', aliases:['Tehran']},
  {key:'isfahan',     name:'이스파한', country:'이란',     region:'중동',  flag:'🇮🇷', tier:'low', aliases:['Isfahan','Esfahan']},
  {key:'shiraz',      name:'시라즈',   country:'이란',     region:'중동',  flag:'🇮🇷', tier:'low', aliases:['Shiraz']},
  {key:'wadirum',     name:'와디럼',   country:'요르단',   region:'중동',  flag:'🇯🇴', tier:'mid', aliases:['Wadi Rum']},
  {key:'aqaba',       name:'아카바',   country:'요르단',   region:'중동',  flag:'🇯🇴', tier:'mid', aliases:['Aqaba']},
  {key:'casablanca',  name:'카사블랑카',country:'모로코', region:'아프리카',flag:'🇲🇦', tier:'low', aliases:['Casablanca']},
  {key:'fez',         name:'페즈',     country:'모로코',   region:'아프리카',flag:'🇲🇦', tier:'low', aliases:['Fez','Fes']},
  {key:'chefchaouen', name:'쉐프샤우엔',country:'모로코', region:'아프리카',flag:'🇲🇦', tier:'low', aliases:['Chefchaouen','블루시티']},
  {key:'tunis',       name:'튀니스',   country:'튀니지',   region:'아프리카',flag:'🇹🇳', tier:'low', aliases:['Tunis']},
  {key:'addisababa',  name:'아디스아바바',country:'에티오피아',region:'아프리카',flag:'🇪🇹',tier:'low',aliases:['Addis Ababa']},
  {key:'kigali',      name:'키갈리',   country:'르완다',   region:'아프리카',flag:'🇷🇼', tier:'low', aliases:['Kigali']},
  {key:'arusha',      name:'아루샤',   country:'탄자니아', region:'아프리카',flag:'🇹🇿', tier:'low', aliases:['Arusha','Serengeti','세렝게티']},
  {key:'lagosng',     name:'라고스(나이지리아)',country:'나이지리아',region:'아프리카',flag:'🇳🇬',tier:'low',aliases:['Lagos Nigeria']},
  {key:'dakar',       name:'다카르',   country:'세네갈',   region:'아프리카',flag:'🇸🇳', tier:'low', aliases:['Dakar']},
  {key:'windhoek',    name:'빈트후크', country:'나미비아', region:'아프리카',flag:'🇳🇦', tier:'low', aliases:['Windhoek']},
];

/** Build country list from the cities dataset (deduped) */
export function listCountries() {
  const seen = new Set();
  const out = [];
  CITIES.forEach(c => {
    if (seen.has(c.country)) return;
    seen.add(c.country);
    out.push({ key: c.country, name: c.country, flag: c.flag });
  });
  return out;
}

export function citiesIn(country) {
  return CITIES.filter(c => c.country === country);
}

export function findCity(predicate) {
  return CITIES.find(predicate);
}

/** Search by name/aliases/country.  Case + diacritic-insensitive prefix-first match. */
export function searchCities(query, limit = 8) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return [];
  const matches = [];
  for (const c of CITIES) {
    const hay = [c.name, c.country, ...(c.aliases || [])].map(s => s.toLowerCase());
    let score = 0;
    if (hay.some(h => h === q)) score = 100;
    else if (hay.some(h => h.startsWith(q))) score = 60;
    else if (hay.some(h => h.includes(q))) score = 30;
    if (score) matches.push({ c, score });
  }
  matches.sort((a, b) => b.score - a.score);
  return matches.slice(0, limit).map(m => m.c);
}
